version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tiktok_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/database.db # Lưu trữ DB độc lập bên ngoài container
      - BROWSER_HEADLESS=True # Ép chạy ngầm trình duyệt tàng hình trong môi trường Docker
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tiktok_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend_data: