"""Baseline: the schema as it stood before alembic owned it.

⛔ THIS REVISION DOES NOTHING, ON PURPOSE. Until today the schema was migrated
by `SQLModel.metadata.create_all()` plus a list of hand-written
`PRAGMA table_info` / `ALTER TABLE ADD COLUMN` steps that ran on every startup
(connection.py). Those steps are SQLite-only and have no notion of a schema
version, so there was nothing to migrate from and nothing to migrate back to.

Real customer databases already exist in that shape - 2115 account rows in the
one measured here - and an autogenerated baseline that tried to CREATE those
tables would fail against every one of them.

(An earlier draft of this note read "2115 rows, of which the API lists 1974",
which was wrong: 1974 was a count taken on 04/10/2026 and 2115 one taken on
06/10, and 166 accounts were imported on the 05th. Nothing filters the list.) So the boundary is drawn
here instead: whatever shape a database is in when it first meets alembic is
declared to be this revision, and alembic owns every change after it.

Which is why `init_db()` runs the legacy catch-up first, then stamps this
revision, and only then upgrades. The catch-up is what brings an OLD database
up to this baseline; stamping without it would tell alembic a database has
columns it may not have.

The baseline schema itself stays defined by the SQLModel models, which remain
the single source of truth - deliberately not copied into a 400-line
autogenerated file here that would drift from them.
"""
from __future__ import annotations

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
